### ISSUE TITLE
Wasp on AND box opens. Wasp stays on. Box close=unoccupied

### ISSUE THREAD

**Issue by calisro** [dlashua/hass-wasp_sensor#1]
**Is your feature request related to a problem? Please describe.**

If a wasp is on and a box is opened and then closed, if that wasp REMAINS on for the duration the occupancy will show off even though that wasp is active.  If that wasp changes state, things work normally.

**Describe the solution you'd like**

I'd like to see the state of a wasp checked upon the timeout and if the box is closed but the wasp REMAINS active, the box should be considered occupied. It shouldn't wait for the state to actually CHANGE to trigger the occupancy again.

**Describe alternatives you've considered**

**Additional context**

**Comment by dlashua** [comment]
I believe this is the intended operation.

Most available sensors do not instantly report when motion stops. They range from 6 seconds to 5 minutes from what I've seen.

If you have a 5 minute variety... someone enters the room: box turns "open", wasp turns "on" shortly there after. They do something for 10 seconds and then leave, closing the door behind them. box turns "closed". At this point, wasp is still "on". It will turn off in 4 minutes and 50 seconds or so.

The "timeout" configuration parameter can assist with this.  By setting timeout to the number of seconds your particular sensors take to report "no motion", the wasp sensor will maintain the "occupied" state if the wasp sensor stays on for that amount of time after the box is closed.

**Comment by dlashua** [comment]
I think I may have misunderstood your issue. If any "wasp" is on the "occupancy" should be on. Regardless of the state of the "box". I'll look into this.

**Comment by dlashua** [comment]
No, I was right the first time. This entity is intended to only be "on" when it is known that a wasp is TRAPPED in the box. If there is a wasp in the box (motion) but the box is not closed (a door is open) then this sensor should be "off". For a true occupancy sensor, you likely want to include both motion and the wasp sensor, as is shown in this project's README.

**Comment by calisro** [comment]
I still think this is wrong and it doesn't agree with other wasp detection programs.  I've recorded a video with how App Daemon wasp-in-a-box works and this one based on the same input_binary sensors.  You'll see pretty quickly the issue.  If this is the way it is intended on working, that is fine.  But this is a problem for most use cases:

AppDaemon Wasp in a box:
```
wasptestad:
  module: wasp
  class: Wasp
  device_class: occupancy
  name: wasptestad
  delay: 5
  box_sensors:
    - input_boolean.wasp_box
  wasp_sensors:
    - input_boolean.wasp_pir
```

This GIT Wasp sensor:
```
wasp_sensor:
  - name: wasptest
    timeout: 5
    wasp_sensors:
      - input_boolean.wasp_pir
    box_sensors:
      - input_boolean.wasp_box
```

https://user-images.githubusercontent.com/5018276/161281314-a666e858-576e-4dc4-a84d-324346eb70c4.mp4

  
At the end of the day, i'll use App Daemon but was looking to use the inverse functionality here and not bake in appdaemon.  I can see the use case for both ways.  It would be nice to be able to configure this behavior with a flag. Something like 'box on during wasp activity' or something.
